#ifndef CONSTANTS_H
#define CONSTANTS_H

//window constants
#define OPENGL_VERSION_MAJOR 4
#define OPENGL_VERSION_MINOR 6
#define TARGET_UPS 200
#define TARGET_FPS 60

//voxel engine constants
#define CHUNK_SIZE 16
#define CHUNK_HEIGHT 128
#define CHUNK_AREA (CHUNK_SIZE * CHUNK_SIZE)
#define CHUNK_VOLUME (CHUNK_SIZE * CHUNK_HEIGHT * CHUNK_SIZE)
#define BLOCK_DATA_STRIDE 9
#define BLOCK_SIDE_DATA (6 * BLOCK_DATA_STRIDE)
#define BLOCK_SIDES 6
#define BLOCKS 5
#define TEXTURES_IN_ATLAS_WIDTH 3
#define TEXTURES_IN_ATLAS_HEIGHT 2
#define TEXTURES_IN_ATLAS (TEXTURES_IN_ATLAS_WIDTH * TEXTURES_IN_ATLAS_HEIGHT)

#endif